const MixData = [
    {
      id: 1,
      img: "https://liveorganic.co.in/cdn/shop/products/20_French_beans_250g.jpg?v=1659420692",
      name: "French Beans 250G",
      price: 150,
      desc: "Thin and cylindrical in shape, French Ring beans come with plump notches that enclose the peas inside. Peas are lime green in colour and semi starchy with sweet and grassy flavours.",
      category: "Vegitable",
      rating: 4.5,
    },
    {
      id: 2,
      img: "https://liveorganic.co.in/cdn/shop/products/23_Karela_250g.jpg?v=1659420697",
      name: "Karela 250G",
      price: 130,
      desc: "Karela, also known as bitter gourd, is a vegetable that is known for its numerous health benefits. This vegetable has a bitter taste, but it is full of essential nutrients that can help maintain good health.",
      category: "Vegitable",
      rating: 4.2,
    },
    {
      id: 3,
      img: "https://liveorganic.co.in/cdn/shop/products/19_cucumber_500g.jpg?v=1659420690",
      name: "Cucumber 500G",
      price: 160,
      desc: "Cucumbers are commonly mistaken for vegetables. But in fact they are fruits, specifically berries. The long, green berries of the cucumber plant are what you usually find in your salads and sandwiches",
      category: "Vegitable",
      rating: 4.6,
    },
    {
      id: 4,
      img: "https://liveorganic.co.in/cdn/shop/products/25_Lauki_1_pc.jpg?v=1659420701",
      name: "Lauki 400 - 500 Grams",
      price: 140,
      desc: "Lagenaria siceraria, known as bottle gourd in English and Lauki in Hindi, is a common vegetable in India. Bottle gourd has been used traditionally to help with many health conditions like fever,.",
      category: "Vegitable",
      rating: 4.2,
    },
    {
      id: 5,
      img: "https://liveorganic.co.in/cdn/shop/products/Coriander.jpg?v=1660271817",
      name: "Coriander 150g-200g",
      price: 170,
      desc: "Coriander has multiple health benefits. Coriander is a wonderful source of dietary fiber, manganese, iron and magnesium as well.",
      category: "Vegitable",
      rating: 4.8,
    },
    {
      id: 6,
      img: "https://liveorganic.co.in/cdn/shop/products/22_Ginger_250g.jpg?v=1659420696",
      name: "Ginger Fresh 200G",
      price: 80,
      desc: "Firm and fibrous Ginger roots are stretched with multiple fingers that have light to dark tan skin and rings on it and is aromatic, spicy and pungent. The flavour gets intensified when the ginger is dried and lessens when cooked",
      category: "Vegitable",
      rating: 4.5,
    },
    {
      id: 7,
      img: "https://liveorganic.co.in/cdn/shop/products/21_Garlic_250g.jpg?v=1659420694",
      name: "Garlic 200 G",
      price: 110,
      desc: "Garlic is an onion species with a very distinct flavour and an overwhelming aroma. It is equally used for culinary and medicinal purposes. Garlic can be stir fried, ground or grated before adding to main courses, ",
      category: "Vegitable",
      rating: 4.2,
    },
    {
      id: 8,
      img: "https://liveorganic.co.in/cdn/shop/products/26_Lemons_250g.jpg?v=1659420702",
      name: "Lemon 200 g",
      price: 95,
      desc: "Enjoy a healthy and refreshing breakfast with layers of creamy Greek yogurt, fresh berries, honey, and granola. A balanced option that provides a burst of flavors and energy.",
      category: "Vegitable",
      rating: 4.1,
    },
    {
      id: 9,
      img: "https://liveorganic.co.in/cdn/shop/products/buttonmushroom.jpg?v=1661597446",
      name: "Mushroom Button 200 g (Natural)",
      price: 120,
      desc: "Savor the creaminess of mashed avocado on toasted whole grain bread, topped with a sprinkle of sea salt and red pepper flakes. A trendy and nutritious breakfast choice.",
      category: "Vegitable",
      rating: 4.6,
    },
    {
      id: 10,
      img: "https://liveorganic.co.in/cdn/shop/products/37_Tomatoes_500t.jpg?v=1659420724",
      name: "Tomato 500g",
      price: 85,
      desc: "Warm up with a bowl of hearty oatmeal packed with mixed fruits, nuts, and a drizzle of honey. A wholesome breakfast that provides a satisfying start to your day.",
      category: "Vegitable",
      rating: 4.5,
    },
    {
      id: 11,
      img: "https://www.bigbasket.com/media/uploads/p/l/20000708_14-fresho-pomegranate.jpg",
      name: "fresho! Pomegranate, 1 kg",
      price: 190,
      desc: "Delight in a perfectly grilled salmon fillet seasoned with herbs and served with a side of roasted vegetables. A healthy and flavorful dinner option that's rich in omega-3 fatty acids.",
      category: "Fruits",
      rating: 4.5,
    },
    {
      id: 12,
      img: "https://www.bigbasket.com/media/uploads/p/l/1200345_2-bb-combo-mango-banganpalli.jpg",
      name: "bb Combo Mango - Banganpalli, 3 kg Combo",
      price: 160,
      desc: "Indulge in creamy fettuccine Alfredo pasta with tender pieces of grilled chicken. This comforting dinner dish is a blend of pasta, rich Alfredo sauce, and savory chicken.",
      category: "Fruits",
      rating: 4.8,
    },
    {
      id: 13,
      img: "https://www.bigbasket.com/media/uploads/p/l/40325851_1-fresho-dasheri-mango.jpg",
      name: "fresho! Dasheri Mango, 1 kg",
      price: 130,
      desc: "Enjoy a medley of colorful vegetables stir-fried in a flavorful sauce, served over steamed rice. A light and nutritious dinner that's both satisfying and wholesome.",
      category: "Fruits",
      rating: 4.2,
    },
    {
      id: 14,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000031_21-fresho-banana-yelakki.jpg",
      name: "fresho! Banana - Yelakki, 1 kg",
      price: 160,
      desc: "Savor the flavors of a delicious burrito bowl with tender grilled chicken, black beans, rice, sautéed peppers and onions, shredded cheese, and a drizzle of zesty cilantro-lime dressing. A hearty and satisfying chicken dinner option.",
      category: "Fruits",
      rating: 4.6,
    },
    {
      id: 15,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000207_24-fresho-watermelon-small.jpg",
      name: "fresho! Watermelon - Small, 1 pc 1.7 - 2.5 kg",
      price: 175,
      desc: "Indulge in creamy and flavorful mushroom risotto, made with Arborio rice, sautéed mushrooms, and a touch of Parmesan cheese. A comforting and sophisticated dinner choice.",
      category: "Fruits",
      rating: 4.5,
    },
    {
      id: 16,
      img: "https://www.bigbasket.com/media/uploads/p/l/30009286_9-fresho-blueberry.jpg",
      name: "fresho! Blueberry, 125 g",
      price: 120,
      desc: "Enjoy a variety of artisan cheeses, paired with an assortment of crispy crackers and complemented by fresh fruits and nuts. A delightful snack option for sharing or indulging in on your own.",
      category: "Fruits",
      rating: 4.3,
    },
    {
      id: 17,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000582_12-fresho-banana-red.jpg",
      name: "fresho! Banana - Red, 1 kg",
      price: 130,
      desc: "Savor the satisfying crunch of crispy chicken wings seasoned to perfection. Choose your favorite sauce, from tangy BBQ to spicy buffalo, for a flavorful snacking experience.",
      category: "Fruits",
      rating: 4.4,
    },
    {
      id: 18,
      img: "https://www.bigbasket.com/media/uploads/p/l/30009286_9-fresho-blueberry.jpg",
      name: "fresho! Blueberry, 125 g",
      price: 130,
      desc: "Enjoy succulent pieces of marinated paneer (Indian cottage cheese) skewered and grilled to perfection. Served with mint chutney, these paneer tikka skewers offer a flavorful and aromatic Indian snack experience.",
      category: "Fruits",
      rating: 4.9,
    },
    {
      id: 19,
      img: "https://www.bigbasket.com/media/uploads/p/l/20000911_33-fresho-kiwi-green.jpg",
      name: "fresho! Kiwi - Green, 3 pcs (Approx. 220 g - 260 g)",
      price: 90,
      desc: "Relish the smooth and flavorful hummus accompanied by a variety of fresh vegetable sticks and pita bread. A nutritious and satisfying option for a light and refreshing snack.",
      category: "Fruits",
      rating: 4.4,
    },
    {
      id: 20,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000369_13-fresho-guava.jpg",
      name: "fresho! Guava (Loose), 1 kg",
      price: 70,
      desc: "Indulge in a colorful assortment of fruit skewers featuring juicy chunks of melon, berries, pineapple, and more. A sweet and refreshing snack that's both delicious and visually appealing.",
      category: "Fruits",
      rating: 4.8,
    },
  ];
  export default MixData;